workflows:
  version: 2
  build:
    jobs:
      - unit-test
      - say-hello:
          requires:
            - unit-test

version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - run: mvn dependency:go-offline
      - run:
          name: Build and unit test
          command: |
            mvn test -B \
      - store_test_results:
          path: target/surefire-reports


  say-hello:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Nic specialnego, po prostu napisz na konsoli "Hello"
          command: |
            echo Hello
