workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test
version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - continuous-{{ checksum "pom.xml" }}
            - continuous
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: continuous-{{ checksum "pom.xml" }}
      - run:
          name: Build and unit test
          command: |
            mvn test

  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - continuous-{{ checksum "pom.xml" }}
            - continuous
      - run:
          name: Login to docker repo
          command: docker login -u _json_key -p "$GOOGLE_AUTH" https://gcr.io
      - run:
          name: Build image
          command: |
            mvn compile jib:build -DskipTests=true \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
      - run:
          name: send echo when finish
          command: |
          echo finito 6