workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test

version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - continuous-{{ checksum "pom.xml" }}
            - continuous
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: continuous-{{ checksum "pom.xml" }}
      - run:
          name: Build and unit test
          command: |
            mvn test -B
      - store_test_results:
          path: target/surefire-reports


  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - continuous-{{ checksum "pom.xml" }}
            - continuous
      - run:
          name: Say Hello
          command: |
            echo Hello
